version: 2.1
defaults: &defaults
  working_directory: /tmp/persist_to_workspace
  docker:
    - image: juntoseguros/devops:python

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls -lart
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
             - .

  bash:
    <<: *defaults
    steps:
      - run: /bin/bash

  get-cnpj-data:
    <<: *defaults
    steps:
      - run: ls -lart
      - run:
          name: Get and Parse CNPJ Data
          command: /tmp/persist_to_workspace/get_cnpj_data.sh /tmp/persist_to_workspace/links
  
  data-to-csv:
    <<: *defaults
    steps:
      - run:
          name: Convert CNPJ Data to CSV
          command: /tmp/persist_to_workspace/cnpj_data_to_csv.sh

  feed-to-es:
    <<: *defaults
    steps:
      - run: ls -l /tmp/cnpj_csv
      - run: echo "feed CSV to ElasticSearch"
  
workflows:
  version: 2.1
  workflow-project:
    jobs:
      - bash:
          context: GitJMSeguradora
          filters:
            branches:
              only: feat/circleci
      - checkout:
          context: GitJMSeguradora
          filters:
            branches:
              only: feat/circleci
      - get-cnpj-data:
          context: GitJMSeguradora
          requires:
            - checkout
          filters:
            branches:
              only: feat/circleci
      - data-to-csv:
          context: GitJMSeguradora
          requires:
            - get-cnpj-data
          filters:
            branches:
              only: feat/circleci
      - feed-to-es:
          context: GitJMSeguradora
          requires:
            - data-to-csv
          filters:
            branches:
              only: feat/circleci
