version: 2.1

parameters:
  version:
    default: '2019_4'
    type: string
    description: Sufix for the ElasticSearch index

defaults: &defaults
  working_directory: /tmp/persist_to_workspace
  docker:
    - image: juntoseguros/devops:python

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls -lart
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
             - .

  get-csv-s3:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run: echo "check and download s3 for CSVs"
      - run: ./get_csv_s3.sh << pipeline.parameters.version >>
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
            - .

  get-cnpj-data:
    <<: *defaults
    parameters:
      links:
        description: File containing downloadable links
        type: string
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - when:
          condition: 
      - run: ls -lart
      - run: if [ -f s3.lock ]; then circleci step halt; fi
      - run:
          name: Get and Parse CNPJ Data
          command: ./get_cnpj_data.sh << parameters.links >>
          no_output_timeout: 90m
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
            - ./data
  
  data-to-csv:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run: ls -lah ./data || true
      - run: if [ -f s3.lock ]; then circleci step halt; fi
      - run:
          name: Convert CNPJ Data to CSV
          command: ./cnpj_data_to_csv.sh << pipeline.parameters.version >>
          no_output_timeout: 30m
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
            - ./csv

  feed-to-es:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run: ls -lah /tmp/persist_to_workspace/csv
      - run: python csv2es.py << pipeline.parameters.version >> $ES_URL
  
workflows:
  version: 2.1
  workflow-project:
    jobs:
      - checkout:
          context: GitJMSeguradora
          filters:
            branches:
              only: feat/circleci

      - get-csv-s3:
          context: GitJMSeguradora
          requires:
            - checkout
          filters:
            branches:
              only: feat/circleci
  
      - get-cnpj-data:
          name: get-cnpj-data-1
          context: GitJMSeguradora
          links: data_links/links_1
          requires:
            - checkout
            - get-csv-s3
          filters:
            branches:
              only: feat/circleci
      - get-cnpj-data:
          name: get-cnpj-data-2
          context: GitJMSeguradora
          links: data_links/links_2
          requires:
            - checkout
            - get-csv-s3
          filters:
            branches:
              only: feat/circleci
      # - get-cnpj-data:
      #   name: get-cnpj-data-3
      #   context: GitJMSeguradora
      #   links: data_links/links_3
      #   requires:
      #     - checkout
      #   filters:
      #     branches:
      #       only: feat/circleci
      # - get-cnpj-data:
      #   name: get-cnpj-data-4
      #   context: GitJMSeguradora
      #   links: data_links/links_4
      #   requires:
      #     - checkout
      #   filters:
      #     branches:
      #       only: feat/circleci
      # - get-cnpj-data:
      #   name: get-cnpj-data-5
      #   context: GitJMSeguradora
      #   links: data_links/links_5
      #   requires:
      #     - checkout
      #   filters:
      #     branches:
      #       only: feat/circleci
      - data-to-csv:
          context: GitJMSeguradora
          requires:
            - get-cnpj-data-1
            - get-cnpj-data-2
          filters:
            branches:
              only: feat/circleci
      - feed-to-es:
          context: GitJMSeguradora
          requires:
            - data-to-csv
            - get-csv-s3
          filters:
            branches:
              only: feat/circleci

