version: 2.1

defaults: &defaults
  working_directory: /tmp/persist_to_workspace
  docker:
    - image: juntoseguros/devops:python

parameters:
  version:
    default: '2019_4'
    type: string
    description: Sufix for the ElasticSearch index
  s3-csv-lockfile:
    default: 's3-csv.lock'
    type: string
    description: Default name for Lockfile

commands:
  lockfile-halt:
    description: "Halt if lockfile file exists"
    parameters:
      lockfile:
        type: string
        default: << pipeline.parameters.s3-csv-lockfile >>
    steps:
      - run:
          name: Halt if lockfile '<< parameters.lockfile >>' exists
          command: if [ -f << parameters.lockfile >> ]; then circleci step halt; fi

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls -lart
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
             - .

  get-csv-s3:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run: 
          name: Get CSV from S3
          command: ./.circleci/workflows/get-csv-s3.sh << pipeline.parameters.version >> << pipeline.parameters.s3-csv-lockfile >>
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
            - .

  get-cnpj-data:
    <<: *defaults
    parameters:
      links:
        description: File containing downloadable links
        type: string
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run: 
          name: List all workspace files
          command: ls -lart
      - lockfile-halt
      - run:
          name: Get CNPJ Data
          command: ./.circleci/workflows/get-cnpj-data.sh << parameters.links >>
          no_output_timeout: 90m
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
            - ./data
  
  data-to-csv:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run:
          name: List all Data files
          command: ls -lah ./data || true
      - lockfile-halt
      - run:
          name: Convert CNPJ Data to CSV
          command: ./.circleci/workflows/data2csv.sh
          no_output_timeout: 30m
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
            - ./csv

  csv-to-s3:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - lockfile-halt
      - run:
          name: CSV to S3
          command: ./.circleci/workflows/csv2s3.sh << pipeline.parameters.version >>
          no_output_timeout: 30m

  feed-to-es:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run:
          name: List all CSV files
          command: ls -lah /tmp/persist_to_workspace/csv
      - run:
          name: Publish data to ElasticSearch
          command: python3 csv2es.py << pipeline.parameters.version >> $ES_URL
          no_output_timeout: 30m
  
workflows:
  workflow-project:
    jobs:
      - checkout:
          context: GitJMSeguradora
          filters:
            branches:
              only: feat/circleci

      - get-csv-s3:
          context: GitJMSeguradora
          requires:
            - checkout
          filters:
            branches:
              only: feat/circleci
  
      - get-cnpj-data:
          name: get-cnpj-data-1
          context: GitJMSeguradora
          links: data_links/links_1
          requires:
            - checkout
            - get-csv-s3
          filters:
            branches:
              only: feat/circleci
      - get-cnpj-data:
          name: get-cnpj-data-2
          context: GitJMSeguradora
          links: data_links/links_2
          requires:
            - checkout
            - get-csv-s3
          filters:
            branches:
              only: feat/circleci
      - get-cnpj-data:
          name: get-cnpj-data-3
          context: GitJMSeguradora
          links: data_links/links_3
          requires:
            - checkout
            - get-csv-s3
          filters:
            branches:
              only: feat/circleci
      - get-cnpj-data:
          name: get-cnpj-data-4
          context: GitJMSeguradora
          links: data_links/links_4
          requires:
            - checkout
            - get-csv-s3
          filters:
            branches:
              only: feat/circleci
      - get-cnpj-data:
          name: get-cnpj-data-5
          context: GitJMSeguradora
          links: data_links/links_5
          requires:
            - checkout
            - get-csv-s3
          filters:
            branches:
              only: feat/circleci

      - data-to-csv:
          context: GitJMSeguradora
          requires:
            - get-cnpj-data-1
            - get-cnpj-data-2
          filters:
            branches:
              only: feat/circleci
      - csv-to-s3:
          context: GitJMSeguradora
          requires:
            - data-to-csv
            - get-csv-s3
      - feed-to-es:
          context: GitJMSeguradora
          requires:
            - data-to-csv
            - get-csv-s3
          filters:
            branches:
              only: feat/circleci

