version: 2.1
defaults: &defaults
  working_directory: /tmp/persist_to_workspace
  docker:
    - image: juntoseguros/devops:python

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls -lart
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
             - .

  get-cnpj-data:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run: ls -lart
      - run:
          name: Get and Parse CNPJ Data
          command: ./get_cnpj_data.sh links
          no_output_timeout: 30m
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
            - .
  
  data-to-csv:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run: ls -lart
      - run:
          name: Convert CNPJ Data to CSV
          command: ./cnpj_data_to_csv.sh
          no_output_timeout: 30m
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
            - .

  feed-to-es:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run: ls -l /tmp/cnpj_csv
      - run: echo "feed CSV to ElasticSearch"
  
workflows:
  version: 2.1
  workflow-project:
    jobs:
      - checkout:
          context: GitJMSeguradora
          filters:
            branches:
              only: feat/circleci
      - get-cnpj-data:
          context: GitJMSeguradora
          requires:
            - checkout
          filters:
            branches:
              only: feat/circleci
      - data-to-csv:
          context: GitJMSeguradora
          requires:
            - get-cnpj-data
          filters:
            branches:
              only: feat/circleci
      - feed-to-es:
          context: GitJMSeguradora
          requires:
            - data-to-csv
          filters:
            branches:
              only: feat/circleci
