
def get_header_index(column):
    header = {
        'cnpj': 0,
        'matriz_filial': 1,
        'razao_social': 2,
        'nome_fantasia' : 3,
        'situacao' : 4,
        'data_situacao' : 5,
        'motivo_situacao' : 6,
        'nm_cidade_exterior' : 7,
        'cod_pais' : 8,
        'nome_pais' : 9,
        'cod_nat_juridica' : 10,
        'data_inicio_ativ' : 11,
        'cnae_fiscal' : 12,
        'tipo_logradouro' : 13,
        'logradouro' : 14,
        'numero' : 15,
        'complemento' : 16,
        'bairro' : 17,
        'cep' : 18,
        'uf' : 19,
        'cod_municipio' : 20,
        'municipio' : 21,
        'ddd_1' : 22,
        'telefone_1' : 23,
        'ddd_2' : 24,
        'telefone_2' : 25,
        'ddd_fax' : 26,
        'num_fax': 27,
        'email' : 28,
        'qualif_resp' : 29,
        'capital_social' : 30,
        'porte' : 31,
        'opc_simples' : 32,
        'data_opc_simples' : 33,
        'data_exc_simples' : 34,
        'opc_mei' : 35,
        'sit_especial' : 36,
        'data_sit_especial' : 37
    }

    return header[column]